### ISSUE TITLE
Bug Report: Remove extension warning does not work on MSEdge

### ISSUE THREAD

**Issue by kien5436** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#69] opened 2021-09-07 00:59 UTC
**Describe your problem in one sentence:**
It's simply not working on MSEdge

**Name the affected patch/problem (if available)**
Remove extension warning

**Your used browser**
Microsoft Edge
Version 93.0.961.38 (Official build) (64-bit)

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/23404165/132269119-16e4f428-c2dd-4189-bae3-db1c41cd369f.png)

**Longer description (optional)**
 Explain how you encountered the bug or what it is about in detail.

**Additional information (optional)**
Add any other information about the problem here.

**Comment by Ceiridge** [comment] 2021-09-07 01:33
The issue is not reproducible on my machine and I have also checked the patterns and offsets and everything is still correct. You might have incorrectly installed the injector or it is not running or similar.

**Comment by kien5436** [comment] 2021-09-07 12:57
The injector always run, I can see its process in task manager. I guess I pick wrong path. Here are my steps:
- Run the injector with admin right
- Select .dll file
- Another window appear, ask me to select .exe file
- Choose "remove extensions warning" patch
- Apply it, result is:

> Patcher gui initialized
Searching for Chromium installations...
Cleared ChromeExes registry
Wrote patch file to C:\Users\kien\AppData\Local\Microsoft\Edge\Application\93.0.961.38
Appended C:\Users\kien\AppData\Local\Microsoft\Edge\Application\93.0.961.38\msedge.dll to the registry key
Extracted injector zip
Wrote patcher dll to C:\Program Files\Ceiridge\ChromeDllInjector\ChromePatcherDll_1631019153.2268045.dll
Created and started task
Patches installed!
Successfully installed to C:\Users\kien\AppData\Local\Microsoft\Edge\Application\93.0.961.38\msedge.exe

Can you help me where I went wrong?

**Comment by Ceiridge** [comment] 2021-09-07 13:00
Normally you don't have to choose any path, because the installer GUI automatically finds the Edge installation?

**Comment by kien5436** [comment] 2021-09-07 16:21
Sorry for late reply. I don't know that the injector can automatically find path. My Windows doesn't include Edge and I install it from store. But I'm sure I chose the right file

**Comment by Ceiridge** [comment] 2021-09-07 16:27
I'm sure you chose the wrong file.
This should not be happening: `Wrote patch file to C:\Users\kien\AppData\Local\Microsoft\Edge\Application\93.0.961.38
`, instead it should be: `Wrote patch file to C:\Users\kien\AppData\Local\Microsoft\Edge\Application
`

**Comment by kien5436** [comment] 2021-09-07 16:33
Oh, I'll try it. Edge gives me option to disable warning in 2 weeks so I'll notice you result after that

**Comment by Ceiridge** [comment] 2021-09-07 16:34
If you choose the files correctly as stated in this comment (https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/issues/69#issuecomment-914302873), it should work.
I will add it to the automatic installation finder in the future (https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/issues/70).

**Comment by kien5436** [comment] 2021-09-21 12:57
I tried as you said but the injector didn't work

![image](https://user-images.githubusercontent.com/23404165/134174058-39a48cfe-18b0-47aa-8799-e07fc78f6500.png)

**Comment by Ceiridge** [comment] 2021-09-21 13:26
You can try looking up the actual executable path of msedge.exe by performing a right click on the Edge process (you might have to expand the group of Edge processes first) in the task manager and by clicking on "Open file location".

If this doesn't help, please send these log files located at these paths:
`C:\Windows\Temp\ChromePatcherDll.log`
`C:\Windows\Temp\ChromePatcherDllErr.log`
`C:\Windows\Temp\ChromePatcherInjector.log` (might require Administrator permissions to read, so try copying the file to another location)
`C:\Windows\Temp\ChromePatcherInjectorErr.log` (might require Administrator permissions to read, so try copying the file to another location)

**Comment by kien5436** [comment] 2021-09-21 13:50
I can't find ChromePatcherInjectorErr.log. Here are log files:
[ChromePatcherDll.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/7203585/ChromePatcherDll.log)
[ChromePatcherDllErr.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/7203588/ChromePatcherDllErr.log)
[ChromePatcherInjector.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/7203592/ChromePatcherInjector.log)

**Comment by Ceiridge** [comment] 2021-09-21 16:28
I just tried the patcher again in a virtual machine with the latest version and the patcher fully worked. Maybe your antivirus does something strange. I will leave this issue open to make sure this is only a single case and not an actual bug.

**Comment by kien5436** [comment] 2021-09-21 23:34
Ok. I think I have to deal with it. Anw, thanks for your time

**Comment by Ceiridge** [comment] 2023-04-15 20:50
This is now actually a duplicate of #95
The discussion goes on further there

**Closed by Ceiridge** 2023-04-15 20:50 UTC
Labels: bug, unreproducible
