### ISSUE TITLE
Bug Report: Extension warnings reappearing in Edge

### ISSUE THREAD

**Issue by MonfGeiger** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#95] opened 2023-02-09 20:15 UTC
**Describe your problem in one sentence:**
I use the patcher, it stops the warnings for a while, but then the dev extension warnings happen again

**Name the affected patch/problem (if available)**
The "Dev Extension Warning" patch acting less of a permanent-ish removal/hider and more of a "temp sleep mode" patch

**Your used browser**
Microsoft Edge 109.0.1518.70

**Screenshots (optional)**
![pat1](https://user-images.githubusercontent.com/28603306/217924056-db0f0e8d-7c7d-43b9-a057-4dad98401fa6.png)
![pat2](https://user-images.githubusercontent.com/28603306/217924066-1aeb1994-3a46-4aa4-b768-154d034b2bdd.png)

**Longer description (optional)**
About two weeks ago, i had to fix some edge stuffs, so after making sure the warning patch was uninstalled, i repair installed edge using the setup file downloaded from the microsoft edge webpage, re-configured stuff back to how i had it, and re-applied the warning patch again. the 1st screenshot has the patches im using, the 2nd is the (Re)-Install output. for a time, it worked, not a single "hey, this is a dev extension, best to not use it or whatever, set this warning in sleep mode and blah blah idgaf". I don't use edge as much except for youtube or certain websites that (for **_SOME_** dumb reason or another) have compatibility problems or issues with firefox. well, at the time of this post, the warning came back. so i reinstalled the patch with the same choices i chose last time, and for now, it hasn't come back. idk if its my version number of edge, or the patching tool being out of date or something, but even if the patch tool needs to be constantly running to permanently hide the warning, somehow said warning still squeaking by.

**Additional information (optional)**
No Password
[Patch Tool Log (only three).zip](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/10701154/Patch.Tool.Log.only.three.zip)

Version of the patch tool is 6.0.0
This feels almost the same as this issue below, but i think its different enough, so ill put it as reference (also, nice)
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/issues/69

**Comment by Ceiridge** [comment] 2023-02-09 20:18
When you get the extension warning in Edge, do you click on *Not now* or on *Remind me in 2 weeks*?

**Comment by MonfGeiger** [comment] 2023-02-10 04:47
i click on the X button. sometimes, that makes it go away for a long while, while on the most random of times (by random, i do indeed mean non-consistently), when i open edge, it just pops back up again. its ephemeral on when & if it happens again. idk if its something edge is auto-fixing about itself (however it may/may not be doing it), or if the 6.0.0 edition of the patch is faltering against the newer version-updates of edge, but that's what im getting

**Comment by Ceiridge** [comment] 2023-02-10 04:52
It could be that it is not injecting fast enough. Also try just clicking on *Not now* next time. Also make sure that no Edge process is running before you start Edge and after you close it. Windows 11 especially always keeps an instance running, because Microsoft really wants you to use it. This improves startup time by 0.1 seconds and for that they occupy hundreds of megabytes of RAM by default.
I will look into this myself in the next weeks

**Comment by MonfGeiger** [comment] 2023-02-10 07:10
ah crap, forgot to mention my OS, my bad
Edition	Windows 10 Pro
Version	22H2
Installed on	‎10/‎29/‎2022
OS build	19045.2364

**Comment by Ceiridge** [comment] 2023-03-03 16:56
@MonfGeiger Did the warning appear again?

**Comment by lbmaian** [comment] 2023-03-25 03:03
I'm getting this too for the past couple weeks.
Disabled "continue running background extensions..." option and ensured no msedge.exe when running the patcher.
OS: Windows 10 Pro build 19045.2728
Tried the "Not now" -> "Remind on browser restart" option, but it didn't work.
Of course, "Not now" -> "Remind in 2 weeks" blocks it, but not permanently like the patcher's supposed to.

**Comment by MonfGeiger** [comment] 2023-03-29 17:44
> @MonfGeiger Did the warning appear again?

i think it might've a couple weeks ago, but in the now (at the time of this post), it hasn't reappeared. ill be honest, i forgot about this issue i opened up, but lately i havent been using edge for much, so unless i rapidly open & close edge to proc the warning somehow, it isnt showing just yet

**Comment by Ceiridge** [comment] 2023-04-14 01:42
> > @MonfGeiger Did the warning appear again?
> 
> i think it might've a couple weeks ago, but in the now (at the time of this post), it hasn't reappeared. ill be honest, i forgot about this issue i opened up, but lately i havent been using edge for much, so unless i rapidly open & close edge to proc the warning somehow, it isnt showing just yet

What about now?

**Comment by Gabanders** [comment] 2023-04-15 04:25
I am also currently having this issue. The warning appeared when I opened Edge just now.
No background running process, Startup Boost in settings is turned off.

**Comment by Ceiridge** [comment] 2023-04-15 20:45
I have just tried to reproduce it and the warning did not appear for me once I installed my patcher. After uninstalling the patcher, the warning reappears.

@Gabanders 
Please do the following:
1. Start Edge as normal
2. Locate it in the Task Manager and tell me **the file path of the running `msedge.exe` process** (Find it in the Details tab, then go to the file)
3. Find the `msedge.dll` file located in the same folder or nearby (in a child folder), zip it with any good zip compressor, and then **upload the file** here

**Comment by Gabanders** [comment] 2023-04-16 01:11
My running `msedge.exe` process is located in C:\Program Files (x86)\Microsoft\Edge\Application

The uploaded `msedge.dll` was located in C:\Program Files (x86)\Microsoft\Edge\Application\112.0.1722.46. It was too large to be uploaded directly to Github so I uploaded it to my [Google Drive](https://drive.google.com/file/d/1s4xr20BwFfweTWGSBHddmVcl254wrvhx/view?usp=sharing).

**Comment by Ceiridge** [comment] 2023-04-16 01:16
> My running `msedge.exe` process is located in C:\Program Files (x86)\Microsoft\Edge\Application
> 
> The uploaded `msedge.dll` was located in C:\Program Files (x86)\Microsoft\Edge\Application\112.0.1722.46. It was too large to be uploaded directly to Github so I uploaded it to my [Google Drive](https://drive.google.com/file/d/1s4xr20BwFfweTWGSBHddmVcl254wrvhx/view?usp=sharing).

Please open edge://settings/help and let it update to the latest stable version (112.0.1722.48), then do the same steps again. I would like your `112.0.1722.48` msedge.dll

**Comment by Gabanders** [comment] 2023-04-16 01:26
Here is the `112.0.1722.48` version of my msedge.dll: [Google Drive](https://drive.google.com/file/d/1DA0uHlUrSC_Rdv5EqgkN947KDreVl43y/view?usp=share_link).

**Comment by Ceiridge** [comment] 2023-04-16 01:35
@Gabanders 
I have the exact same file and also at the same location.
Can you (re)install the patcher and also send me the logs that the patcher produces?
What antivirus do you use? Do you have a game running with anticheat? Do you have a kernel anticheat installed? Is there anything noteworthy in regards to your system?

**Comment by Yoongbo** [comment] 2023-05-03 11:28
I notice that the extension warning will only pop up when I launch Edge immediately after a reboot before waiting for the ChromeDLLInjector to appear. So the patcher does work but I hope you come up with a different method so we don't have to wait for it to launch first on startup.

**Comment by Ceiridge** [comment] 2023-05-03 16:09
> I notice that the extension warning will only pop up when I launch Edge immediately after a reboot before waiting for the ChromeDLLInjector to appear. So the patcher does work but I hope you come up with a different method so we don't have to wait for it to launch first on startup.

This is hardly possible. It is better to patch during runtime and this requires the injector to be launched.
Computers running with a fast CPU, unlike yours, should be able to launch the injector within 1-10 seconds after logging in.

**Comment by Ceiridge** [comment] 2023-12-29 18:40
Now a duplicate of #98

**Closed by Ceiridge** 2023-12-29 18:40 UTC
Labels: bug
