### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by rophel** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#53] opened 2021-01-14 16:15 UTC
**Describe your problem in one sentence:**
Error:  An error occurred trying to fetch the new patterns.  The program has to exit, as no cached version of the file has been found.  The rest was aborted: Could not create SSL/TLS secure channel.

**Name the affected patch/problem (if available)**
4.5.2

**Your used browser**
Edge 87.0.664.75 

**Screenshots (optional)**

**Longer description (optional)**

**Additional information (optional)**
Running windows version 20H2 (Build 19052.746) which integrated Edge more fully into OS, wondering if that's the issue.

**Comment by Ceiridge** [comment] 2021-01-14 16:34
Duplicate of https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/issues/52

**Closed by Ceiridge** 2021-01-14 16:34 UTC
Labels: bug
