### ISSUE TITLE
Netflix refuses to stream after using this patcher

### ISSUE THREAD

**Issue by kylevessPL** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#1] opened 2020-01-09 11:05 UTC
Great tool, does the job done, the warning stops showing but there is an issue with Netflix which makes me not to use this patcher until this gets fixed (hope it will, thank you in advance). Netflix refuses to stream anymore after patching, an error M7121-1331 occures (this title can't be streamed right now, something like that, every title). Reinstalling chrome solves the problem so the issue comes from something wrong with this patcher for sure. Will be glad for solving it. Thank you for your hard work.

**Comment by Ceiridge** [comment] 2020-01-09 15:32
Are you sure that it's because of the patcher?
Can you make a backup of your _chrome.dll_ (so you won't have to reinstall everything again later) and then make sure that you can watch videos.

Then patch chrome again and tell me if it then won't work anymore.
Also, if it doesn't, please also try to only watch a trailer, because it might have another DRM protection (search for any netflix title on google and watch its trailer, but not in the real netflix user interface so to say)

Maybe a chrome extension causes this error?

**Comment by kylevessPL** [comment] 2020-01-09 15:59
Checked that. Netflix definitely works before patching and stops after running the patcher. Restored chrome.dll and works fine again. Also, disabled all extensions and same thing. So they are not the cause.  Trailers work fine (tried w/o login in incognito mode).

**Comment by Ceiridge** [comment] 2020-01-09 16:11
I think the native netflix DRM (Widevine) detects the patches and prevents your browser from decrypting the video data.

You could try to only patch some things and not all of them, these are the commandline options:
```
ChromeDevExtWarningPatcher.exe [-noDebugPatch] [-noWWWPatch] [-noWarningPatch] [-noWait]

Explanation:
-noDebugPatch: Disables the patch for the warning of debugging extensions (chrome.debugger)
-noWWWPatch: Disables the patch for re-adding the `https` or `www` in a url, because it matters!
-noWarningPatch: Disables the patch for the warning of developer extensions

-noWait: Disables the almost-pointless wait after finishing

Example (only remove the warning of dev extensions);
ChromeDevExtWarningPatcher.exe -noDebugPatch -noWWWPatch
```

If really any patch causes the error to happen, you won't be able to watch DRM-protected videos with the patches enabled.

**Comment by kylevessPL** [comment] 2020-01-09 16:41
Thank you for suggestions. Tried every command and only -noWarningPatch didn't produce the error in Netflix streaming but unfortunately this didn't hide the main warning on Chrome startup I used this patch for. Every other flag made me not able to watch. What a pity.

**Comment by dheeraj-chakilam** [comment] 2020-04-08 03:55
Can confirm that Amazon Prime Video also refuses to stream after patching. This is on Edge (Chromium version) and I'm yet to try the commandline options.

**Comment by Ceiridge** [comment] 2020-04-08 04:06
I think that it's because of a Widevine integrity check. 
I've found a Widevine demo page: https://www.inisoft.tv/demo.php
Can somebody, who has that error, please try to play _Big Buck Bunny - Stereo, 5.1ch_ with the tag _#Widevine_ (image below)?
Tell me if it works and in what quality you can watch it.

![TMta90I](https://user-images.githubusercontent.com/40047520/78743473-01f66380-795f-11ea-8e42-bff79c1f61c7.png)

**Comment by Ceiridge** [comment] 2020-04-14 18:05
@kylevessPL @dheeraj-chakilam

**Comment by dheeraj-chakilam** [comment] 2020-04-14 18:21
So I can confirm that when patched the Widevine video doesn't play. Moreover, when my edge updates (and the patched dll is overwritten), I can play it again.

**Comment by Ceiridge** [comment] 2020-04-14 18:24
This is strange, because it works for me. Can you scroll down on _chrome://components/_ and tell me your Widevine version and maybe try checking it for updates?

**Comment by Ceiridge** [comment] 2020-04-14 18:28
If this doesn't fix it, will you be able to send me your feedback diagnosis data (in your New Edge)?
Hamburger Menu > Help and Feedback > Send Feedback > Click on Diagnosis Data > Click on every clickable category and make a screenshot of it

**Comment by Ceiridge** [comment] 2020-04-15 01:02
@dheeraj-chakilam

**Comment by dheeraj-chakilam** [comment] 2020-04-15 01:12
Blocked by #8

**Comment by dheeraj-chakilam** [comment] 2020-04-15 01:20
Okay so both the windevine video and amazon prime video work now! This is on the latest Chromium Edge 81.0.416.53 and the latest release https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases/tag/3.2

**Comment by Ceiridge** [comment] 2020-04-15 02:49
How did you fix it? I never had any problems with Widevine, so I'm really confused that it suddenly works now

**Comment by dheeraj-chakilam** [comment] 2020-04-15 02:51
Interesting. I just re-installed edge and patched it with the latest release.

**Comment by ismetisc** [comment] 2020-04-23 14:45
do you know why this doesn't work to load dev extension
--load-and-launch-app= ? or do you know another way to load extension?

**Comment by Ceiridge** [comment] 2020-04-23 14:46
@ismetisc https://developer.chrome.com/extensions/getstarted
Scroll down there until you see the first screenshot

**Comment by ismetisc** [comment] 2020-04-23 14:49
@Ceiridge i mean with command line i can start with this --load-and-launch-app= before but now it doesn't work do you know another way with command line?

Thanks for your reply.

**Comment by Ceiridge** [comment] 2020-04-23 14:50
@ismetisc Did it work before you patched Chrome?

**Comment by ismetisc** [comment] 2020-04-23 14:54
@Ceiridge it didn't, patch is ok i was thinking it maybe work after pached but it didn't...

i wonder chrome is pached to load with command line? my chrome version 81.0.4044.122

i am trying to use this --load-and-launch-app= or this --load-extension don't work.. :(

**Comment by Ceiridge** [comment] 2020-04-23 14:58
@ismetisc This patcher has nothing to do with your problem. It disables a warning that you see when opening Chrome. You should then just stop using the command line arguments and do it like what the Google docs recommend to you.

**Comment by 7Elev3n** [comment] 2020-04-25 09:51
I experienced the same issue. I use Brave.
First, I tested Netflix, and it works. Then I backed up the existing chrome.dll file in the BraveSoftware folder. I ran the patching tool, specifying in the GUI to only patch "disable Elision" and "Remove extension warning". Once patched, Netflix gives the error M7121-1331 (indicating a Widevine issue?). Upon replacing the patched Chrome.dll with the backed up version, Netflix runs again.

**Comment by Ceiridge** [comment] 2020-04-25 11:15
@7Elev3n This is strange, because it works for me. Can you scroll down on chrome://components/ and tell me your Widevine version and maybe try checking it for updates?

**Comment by 7Elev3n** [comment] 2020-04-25 11:29
Hey! Thanks for the quick reply. 

`Widevine Content Decryption Module - Version: 4.10.1582.2
Status - Component not updated`

It says 'not updated' because its the most updated version, I think. Else it says "Update Error" and then I can click the button to update it.

**Comment by Ceiridge** [comment] 2020-04-25 11:32
_I tried reinstalling Brave_
So it doesn't work even when it's not patched?

**Comment by 7Elev3n** [comment] 2020-04-25 11:38
My current setup: Brave (clean) with no patch). 
The Big Buck Bunny video with widevine plays, Netflix works, the extension warning exists. 

Previously, when I had the patched Brave:
Big Buck Bunny with widevine plays, BUT Netflix shows the error, extension warning does not exist.

**Comment by Ceiridge** [comment] 2020-04-25 11:41
What operating system are you using?

**Comment by 7Elev3n** [comment] 2020-04-25 11:43
Windows 10 Pro! (also thank you for putting in time and effort to help me resolve this)

I just repatched Brave (just extension warning and Elision patch). Big Buck Bunny vid works, 1080p. But Netflix fails with the same error.

**Comment by Ceiridge** [comment] 2020-04-25 11:43
Could you try starting Brave with this command line argument: `--disable-features=RendererCodeIntegrity`

**Comment by Ceiridge** [comment] 2020-04-25 11:59
@7Elev3n Did it work?

**Comment by 7Elev3n** [comment] 2020-04-25 12:19
Sorry, was afk. 
1) `--disable-features=RendererCodeIntegrity` method: No impact (Netflix still fails, patched Chrome.dll)
2) Windows 8 compatibility + above cmdline: No impact (same as above)
3) Remove cmdline and windows 8 compatibility and restore old Chrome.dll: Netflix works again.

**Comment by gmilner** [comment] 2020-05-01 12:22
Also experiencing the same issue with Amazon Prime and Netflix after patching Chrome. Windows 10 Pro. If I can help at all, let me know

**Comment by Invisible40** [comment] 2020-06-15 18:56
I ran the patch with Remove extension warning and Remove debugging warning both enabled (the other two disabled). This is for the Brave browser. I can not play Netflix or Amazon Prime Video.

Is there a way to restart Brave with the patch disabled?

**Comment by Ceiridge** [comment] 2020-06-15 18:57
@Invisible40 Yes, in the Brave Application installation folder, there's a backup stored. You can delete the current dll and replace it with the backup.
I still can't reproduce this issue and don't know how it happens.

**Comment by Invisible40** [comment] 2020-06-15 19:03
That's weird. If there's anything I can do to help you out, let me know.

**Comment by Dibbyo456** [comment] 2020-06-18 17:12
Can confirm the same issue Netflix refuses to stream after this patch. But you should not use Chrome for Netflix or Amazon Prime Video because on Chrome/Firefox you can only streams 720p where in Internet Explorer or Edge you can stream 1080p. So, better to use Edge for streaming. That's what I'm doing.

**Comment by stroxx** [comment] 2020-07-15 00:10
Hi, I too can confirm this issue, It seems to be that each time the `chrome.dll` is tampered with using the patcher this issue arises. And as others outlined before; each fresh install without the patch doesn't present the same issue. I took the time to patch every feature individually on a fresh `chrome.dll` for each iteration; to see if it was happening due to an isolated feature. However, that was not the case; because as soon as any sort of changes are made to the dll then Netflix no longer works. 

I am currently using Brave Beta. `1.12.86 Chromium: 84.0.4147.85 (Official Build) beta (64-bit) ` on `Windows 10 OS Version 1903. `

Thank you in advance!

**Comment by Dibbyo456** [comment] 2020-07-15 01:38
So, Netflix verifying the Chrome integrity. A single tiny changes will corrupt Netflix.

**Comment by Ceiridge** [comment] 2020-07-17 18:03
Maybe Chrome only checks the chrome.dll for integrity on the hard drive and not in memory, which would be great.
Can @Dibbyo456 or @stroxx

**Comment by stroxx** [comment] 2020-07-17 18:36
It seems that **only** Netflix is affected. I am able to watch the inisoft demos without a problem; but when Netflix is accessed the error is displayed. 
@Ceiridge

**Comment by Ceiridge** [comment] 2020-07-17 19:27
I was now finally able to reproduce this issue with https://demo.castlabs.com/
I can now investigate on it

**Comment by Ceiridge** [comment] 2020-07-20 19:51
@stroxx @Dibbyo456 @Invisible40 Can you all try out the new gui-binaries artifact from the dllpatcher branch? (https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/actions/runs/176149038 (you need to be logged it to download))
I have recoded the entire patcher and it now uses a dll injector with a patcher dll. Please tell me if the default patches work on **Chrome**.

**Comment by Dibbyo456** [comment] 2020-07-21 04:42
I need to reinstall Chrome before using the new patch?

**Comment by Ceiridge** [comment] 2020-07-21 10:06
@Dibbyo456 No, you just need to replace the `chrome.dll` with the `chrome.dll.bck`, if you have patched it before. There are still many bugs that will be fixed soon.

**Comment by Dibbyo456** [comment] 2020-07-21 13:05
For some reason I don't have any backup file of `chrome.dll`

**Comment by Ceiridge** [comment] 2020-07-21 13:12
@Dibbyo456 Then just try to install the new patcher. I suggest you to use the artifacts here: https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/actions/runs/177103538

**Comment by Dibbyo456** [comment] 2020-07-21 13:26
Netflix now streaming..!! Well done. ✌

**Comment by Ceiridge** [comment] 2020-07-21 13:29
@Dibbyo456 Good, tell me if you encounter any bugs. It will be fully released soon

**Comment by Ceiridge** [comment] 2020-07-21 22:12
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases

**Closed by Ceiridge** 2020-07-21 22:12 UTC
Labels: bug, help wanted
